# Makefile for GEMM Engine Top Simulation (FIFO Interface)
# OBSOLETE: Old engine_wrapper testbench has been removed
# Please use Makefile.engine_top instead:
#   make -f Makefile.engine_top run

.PHONY: all clean run

all:
	@echo "============================================================"
	@echo "ERROR: This Makefile is obsolete."
	@echo "Please use: make -f Makefile.engine_top run"
	@echo "============================================================"
	@exit 1

run: all

clean:
	@echo "Use: make -f Makefile.engine_top clean"
	
help:
	@echo "This Makefile is obsolete."
	@echo "Please use Makefile.engine_top for engine_top testbench."
	@echo ""
	@echo "Example: make -f Makefile.engine_top run"
