#!/usr/bin/env python3
"""
Hardware-Accurate GFP GEMM Reference Model

===============================================================================
PURPOSE
===============================================================================
This script generates golden references for GFP GEMM hardware verification.
It implements TWO algorithms for comparison:

1. HARDWARE-ACCURATE ALGORITHM (HardwareGFPCompute class):
   - Matches RTL implementation exactly (compute_engine.sv, gfp8_nv_dot.sv)
   - Used for generating golden reference files
   - This is the PRIMARY algorithm for hardware verification

2. EMULATOR-BASED ALGORITHM (compute_emulator_golden function):
   - Uses the GFP emulator library (group_floating_point.py)
   - May have slight differences from hardware due to implementation details
   - Used for COMPARISON ONLY, not for golden generation

===============================================================================
OUTPUTS
===============================================================================
- golden_B{B}_C{C}_V{V}.hex: HARDWARE-ACCURATE reference (matches RTL)
- golden_B{B}_C{C}_V{V}_emu_NEW.hex: Emulator-based reference (for comparison)
- out.hex: Same as hardware-accurate reference
- Comprehensive comparison metrics (RMSE, max error, match rate)

===============================================================================
HARDWARE-ACCURATE ALGORITHM (from compute_engine.sv)
===============================================================================
For each output element C[i,j]:
  1. Compute 4 group dot products (integer multiply-accumulate)
  2. Align mantissas by maximum exponent across groups
  3. Sum aligned mantissas as integers
  4. Convert GFP result to FP16 with IEEE 754 rounding

V-LOOP ACCUMULATION (matching gfp8_bcv_controller.sv):
For each output element C[i,j] with V Native Vectors:
  1. Compute V dot products (one per Native Vector)
  2. INCREMENTAL ACCUMULATION (pairwise max-align-sum):
     - For v=0: Initialize accumulator with first dot product
     - For v>0: Find max between accumulator and current dot product
     - Align both mantissas to max exponent
     - Sum aligned mantissas and update accumulator
  3. Convert final GFP result to FP16

===============================================================================
USAGE
===============================================================================
  python hardware_gfp_reference_new.py --B 4 --C 4 --V 4

Loads matrices from left.hex and right.hex (generated by generate_nv_hex.py).
"""

import numpy as np
import sys
import struct
import os
import argparse

# Import common utilities from hex_utils (canonical source)
from hex_utils import (
    load_hex_file,
    decode_exponents,
    decode_mantissas,
    setup_emulator_import,
    get_script_dir,
)

# Try to import GFP emulator library (optional, for comparison only)
try:
    import torch
    setup_emulator_import()
    from group_floating_point import GFPTensor, GFPDataType, GFPGemm
    GFP_EMULATOR_AVAILABLE = True
except ImportError as e:
    GFP_EMULATOR_AVAILABLE = False
    print(f"WARNING: GFP emulator library not available: {e}")
    print("         Emulator-based comparison will be skipped.")


# =============================================================================
# HARDWARE-ACCURATE ALGORITHM
# =============================================================================
# This class implements the exact algorithm used in the RTL hardware.
# It should be the PRIMARY source for golden reference generation.
# =============================================================================

class HardwareGFPCompute:
    """
    HARDWARE-ACCURATE GFP computation matching compute_engine.sv behavior.

    This class implements the exact algorithm used in the FPGA RTL:
    - gfp8_group_dot.sv: Group-level integer MAC
    - gfp8_nv_dot.sv: Exponent-aligned summation across groups
    - gfp8_bcv_controller.sv: V-loop incremental accumulation

    USE THIS FOR GOLDEN REFERENCE GENERATION.
    """

    def __init__(self, exp_bits=5, exp_bias=15, group_size=32):
        """
        Initialize hardware GFP parameters.

        Args:
            exp_bits: Number of exponent bits (5 for GFP8)
            exp_bias: Exponent bias (15 for 5-bit exponent)
            group_size: Elements per group (32 for GFP8)
        """
        self.exp_bits = exp_bits
        self.exp_bias = exp_bias
        self.group_size = group_size
        self.num_groups = 4  # For 128-element vectors (128 / 32 = 4)

    def compute_dot_product(self, left_mant, left_exp, right_mant, right_exp):
        """
        Compute dot product of two GFP vectors using HARDWARE-ACCURATE algorithm.

        Matches gfp8_nv_dot.sv exponent-aligned integer summation algorithm.

        Args:
            left_mant: [128] array of left mantissas (int8)
            left_exp: [4] array of left exponents (uint5)
            right_mant: [128] array of right mantissas (int8)
            right_exp: [4] array of right exponents (uint5)

        Returns:
            tuple: (mantissa, exponent) GFP result before FP16 conversion
        """
        group_mantissas = []
        group_exponents = []

        # Step 1: Compute each group dot product (matching gfp8_group_dot.sv)
        for g in range(self.num_groups):
            # Integer accumulation within group
            accumulator = 0
            for i in range(self.group_size):
                elem_idx = g * self.group_size + i
                accumulator += int(left_mant[elem_idx]) * int(right_mant[elem_idx])

            # Calculate exponent: exp_result = exp_left + exp_right - 2*bias
            exp_sum = int(left_exp[g]) + int(right_exp[g]) - 2 * self.exp_bias

            group_mantissas.append(accumulator)
            group_exponents.append(exp_sum)

        # Step 2: Exponent alignment and integer summation (matching gfp8_nv_dot.sv lines 116-134)
        # Find maximum exponent among all 4 groups
        max_exponent = max(group_exponents)

        # Align mantissas by right-shifting to max exponent
        aligned_mantissas = []
        for g in range(self.num_groups):
            exp_diff = max_exponent - group_exponents[g]

            # Check for underflow (matching gfp8_nv_dot.sv line 129-131)
            if exp_diff > 31:
                # Underflow - set to zero
                aligned = 0
            else:
                # Python's >> operator performs arithmetic right shift for negative numbers
                # (same behavior as SystemVerilog's >>> operator)
                aligned = group_mantissas[g] >> exp_diff
            aligned_mantissas.append(aligned)

        # Sum aligned mantissas as integers
        sum_mantissa = sum(aligned_mantissas)

        # Return GFP result (mantissa, exponent) - do NOT convert to float yet!
        # Hardware returns this as GFP, only converts to FP16 after V-loop accumulation
        return (sum_mantissa, max_exponent)

    def gfp_to_fp16(self, gfp):
        """
        Convert GFP (mantissa, exponent) to FP16 format.

        Converts GFP to float, clamps to FP16 range, then converts to FP16
        using IEEE 754 round-to-nearest-even.

        Args:
            gfp: (mantissa, exponent) tuple

        Returns:
            uint16: FP16 representation
        """
        mantissa, exponent = gfp

        # Convert GFP to float
        scale_factor = 2.0 ** exponent
        float_val = float(mantissa) * scale_factor

        # Clamp to FP16 range
        FP16_MAX = 65504.0
        if float_val > FP16_MAX:
            clamped_val = FP16_MAX
        elif float_val < -FP16_MAX:
            clamped_val = -FP16_MAX
        else:
            clamped_val = float_val

        # Convert to FP16 using numpy (IEEE 754 round-to-nearest-even)
        fp16_val = np.float16(clamped_val)
        fp16_bits = fp16_val.view(np.uint16)

        return fp16_bits

    def compute_gemm_with_bcv(self, left_mant, left_exp, right_mant, right_exp, B, C, V, left_start_addr=0, right_start_addr=0):
        """
        Compute GEMM with B, C, V parameters and V-loop accumulation.

        HARDWARE-ACCURATE ALGORITHM:
        Uses hardware algorithm for group dot products, then applies incremental
        accumulation for V-loop (matching gfp8_bcv_controller.sv):
        1. Compute V dot products (one per Native Vector) using compute_dot_product()
        2. INCREMENTAL ACCUMULATION: For each V iteration, find max between
           accumulator and current dot product, align both, sum, update accumulator
        3. Convert final GFP result to FP16

        Args:
            left_mant: [128, 128] left mantissa matrix
            left_exp: [128, 4] left exponent matrix
            right_mant: [128, 128] right mantissa matrix (transposed)
            right_exp: [128, 4] right exponent matrix (transposed)
            B: Output rows (batch size)
            C: Output columns
            V: Inner dimension multiplier (V Native Vectors per output)
            left_start_addr: Starting BRAM address for left matrix (in 4-line units)
            right_start_addr: Starting BRAM address for right matrix (in 4-line units)

        Returns:
            [B*C] array of FP16 results
        """
        results = []

        print(f"   [HARDWARE-ACCURATE] Computing with V-loop accumulation:")
        print(f"   - For each of {B}x{C} outputs: collect {V} dot products")
        print(f"   - Apply incremental accumulation (pairwise max-align-sum)")
        print(f"   - Total: {B*C*V} dot products")

        # Iterate over output positions
        for b in range(B):
            for c in range(C):
                # V-loop: Collect all dot products first
                v_dot_products = []  # List of (mantissa, exponent) tuples

                for v in range(V):
                    # Calculate Native Vector indices with address offset
                    # Address is in 4-line units, so nv_idx = addr / 4
                    left_nv_idx = (left_start_addr // 4) + b * V + v
                    right_nv_idx = (right_start_addr // 4) + c * V + v

                    # Extract vectors for this dot product
                    left_vec_mant = left_mant[left_nv_idx, :]
                    left_vec_exp = left_exp[left_nv_idx, :]
                    right_vec_mant = right_mant[right_nv_idx, :]
                    right_vec_exp = right_exp[right_nv_idx, :]

                    # Compute single NV dot product (returns GFP)
                    dot_gfp = self.compute_dot_product(
                        left_vec_mant, left_vec_exp,
                        right_vec_mant, right_vec_exp
                    )
                    v_dot_products.append(dot_gfp)

                # V-loop accumulation: INCREMENTAL/PAIRWISE (matching hardware)
                # Hardware uses incremental accumulation: for each V iteration,
                # find max between accumulator and new dot product, align both, sum
                # This matches gfp8_bcv_controller.sv lines 223-255
                accumulator_mant = None
                accumulator_exp = None

                for v_idx, (mant, exp) in enumerate(v_dot_products):
                    if v_idx == 0:
                        # First V iteration - initialize accumulator
                        accumulator_mant = mant
                        accumulator_exp = exp
                    else:
                        # Incremental accumulation: find max between accumulator and current dot
                        # Hardware uses signed comparison: $signed(accum_exponent) > $signed(nv_dot_exponent)
                        # Convert to signed 8-bit for comparison (matching hardware)
                        def to_signed8(x):
                            """Convert 8-bit value to signed integer"""
                            return x if x < 128 else x - 256

                        accum_exp_signed = to_signed8(accumulator_exp & 0xFF)
                        exp_signed = to_signed8(exp & 0xFF)

                        # Use signed comparison (matching hardware line 236)
                        if accum_exp_signed > exp_signed:
                            max_exp = accumulator_exp
                        else:
                            max_exp = exp

                        # Align both mantissas to max exponent
                        exp_diff_accum = max_exp - accumulator_exp
                        exp_diff_dot = max_exp - exp

                        if exp_diff_accum > 31:
                            aligned_accum = 0
                        else:
                            # Python's >> performs arithmetic right shift for negative numbers
                            aligned_accum = accumulator_mant >> exp_diff_accum

                        if exp_diff_dot > 31:
                            aligned_dot = 0
                        else:
                            aligned_dot = mant >> exp_diff_dot

                        # Sum aligned mantissas
                        accumulator_mant = aligned_accum + aligned_dot
                        accumulator_exp = max_exp

                # Result is (accumulator_mant, accumulator_exp)
                accumulator_gfp = (accumulator_mant, accumulator_exp)

                # Convert GFP to FP16
                fp16_result = self.gfp_to_fp16(accumulator_gfp)
                results.append(fp16_result)

                # Debug first output
                if b == 0 and c == 0:
                    print(f"   Output[{b},{c}]: {V} dots, final_exp={accumulator_exp}")
                    print(f"                acc_gfp=({accumulator_gfp[0]}, {accumulator_gfp[1]})")
                    print(f"                     -> FP16=0x{fp16_result:04x}")

        return np.array(results, dtype=np.uint16)


# =============================================================================
# EMULATOR-BASED ALGORITHM (for comparison only)
# =============================================================================
# This function uses the GFP emulator library for comparison.
# It may have slight differences from hardware due to implementation details.
# DO NOT USE THIS FOR GOLDEN REFERENCE GENERATION.
# =============================================================================

def compute_emulator_golden(B, C, V, left_mant, left_exp, right_mant, right_exp):
    """
    Generate EMULATOR-BASED golden reference using loaded hex matrices.

    WARNING: This uses the GFP emulator library which may have slight differences
    from the hardware-accurate algorithm. USE FOR COMPARISON ONLY, not for
    golden reference generation.

    Args:
        B: Output rows (batch size)
        C: Output columns
        V: Inner dimension multiplier (V Native Vectors)
        left_mant: [128, 128] left mantissa matrix (from hex)
        left_exp: [128, 4] left exponent matrix (from hex)
        right_mant: [128, 128] right mantissa matrix (from hex)
        right_exp: [128, 4] right exponent matrix (from hex)

    Returns:
        np.array: FP16 results as uint16 array
    """
    if not GFP_EMULATOR_AVAILABLE:
        print("   [EMULATOR] ERROR: GFP emulator library not available!")
        return None

    print(f"\n   [EMULATOR] Computing emulator-based reference (for comparison only)...")
    print(f"   [EMULATOR] WARNING: This may differ from hardware-accurate results!")
    print(f"   [EMULATOR] Loading matrices from hex files (same as hardware path)")

    # Convert GFP hex data to float tensors
    def gfp_to_float_matrix(mant_matrix, exp_matrix, bias=15):
        """Convert GFP (mantissa, exponent) to float matrix."""
        rows, cols = mant_matrix.shape
        float_matrix = np.zeros((rows, cols), dtype=np.float32)
        for i in range(rows):
            for g in range(4):  # 4 groups per row
                group_exp = exp_matrix[i, g]
                scale = 2.0 ** (int(group_exp) - bias)
                for j in range(32):  # 32 elements per group
                    col_idx = g * 32 + j
                    float_matrix[i, col_idx] = float(mant_matrix[i, col_idx]) * scale
        return float_matrix

    # Convert full 128 NV matrices to float
    left_float_full = gfp_to_float_matrix(left_mant, left_exp)
    right_float_full = gfp_to_float_matrix(right_mant, right_exp)

    # Extract submatrices for BxCxV configuration
    left_float = left_float_full[:B*V, :]  # Shape: (B*V) x 128
    right_float = right_float_full[:C*V, :]  # Shape: (C*V) x 128

    # Convert to torch tensors
    left_tensor = torch.from_numpy(left_float).float()
    right_tensor = torch.from_numpy(right_float).float()

    # Create GFP tensors
    gfp_dtype = GFPDataType(
        mantissa_bits=8,
        exp_bits=5,
        exp_bias=15,
        mantissa_signed=True
    )

    gfp_a = GFPTensor(
        original_shape=left_tensor.shape,
        group_axis=1,  # Matrix A: group along columns
        group_size=32,
        dtype=gfp_dtype,
        original_data=left_tensor
    )

    # For Matrix B, we need to transpose since it's stored transposed in hex
    right_tensor_transposed = right_tensor.T  # Shape: 128 x (C*V)
    gfp_b = GFPTensor(
        original_shape=right_tensor_transposed.shape,
        group_axis=0,  # Matrix B: group along rows
        group_size=32,
        dtype=gfp_dtype,
        original_data=right_tensor_transposed
    )

    # Debug: Check dequantized input values
    deq_a = gfp_a.dequantize()
    deq_b = gfp_b.dequantize()
    print(f"   [EMULATOR] Dequantized Matrix A range: [{deq_a.min():.6f}, {deq_a.max():.6f}]")
    print(f"   [EMULATOR] Dequantized Matrix B range: [{deq_b.min():.6f}, {deq_b.max():.6f}]")

    # Define GEMM data types
    product_dtype = GFPDataType(
        mantissa_bits=19,
        exp_bits=8,
        mantissa_signed=True
    )
    accum_dtype = GFPDataType(
        mantissa_bits=20,
        exp_bits=9,
        mantissa_signed=True
    )

    # Run GFP GEMM - computes (B*V) x (C*V) GEMM
    gemm = GFPGemm(accum_dtype=accum_dtype, product_dtype=product_dtype)
    gfp_result = gemm(gfp_a, gfp_b)
    result_full = gfp_result.dequantize().cpu().numpy()  # Shape: (B*V) x (C*V)

    print(f"   [EMULATOR] Full GEMM result shape: {result_full.shape}")
    print(f"   [EMULATOR] Result range: [{result_full.min():.6f}, {result_full.max():.6f}]")

    # V-loop accumulation: sum over V dimension
    # result[b,c] = sum over v of result_full[b*V+v, c*V+v]
    result_accumulated = np.zeros((B, C), dtype=np.float32)
    for b in range(B):
        for c in range(C):
            for v in range(V):
                result_accumulated[b, c] += result_full[b*V + v, c*V + v]

    print(f"   [EMULATOR] Accumulated result shape: {result_accumulated.shape}")

    # Convert to FP16 hex
    result_fp16 = result_accumulated.astype(np.float16).flatten()
    results_emulator = np.array([np.frombuffer(val.tobytes(), dtype=np.uint16)[0] for val in result_fp16], dtype=np.uint16)

    print(f"   [EMULATOR] Generated {len(results_emulator)} FP16 results ({B}x{C})")
    print(f"   [EMULATOR] First 4 values: {' '.join(f'0x{v:04x}' for v in results_emulator[:min(4, len(results_emulator))])}")

    return results_emulator


# =============================================================================
# FLOATING-POINT REFERENCE (for additional comparison)
# =============================================================================

def compute_fp_reference(left_mant, left_exp, right_mant, right_exp, B, C, V, exp_bias=15):
    """
    Compute floating-point reference for comparison.

    This dequantizes the GFP matrices to float and performs standard FP matmul.

    Args:
        left_mant: [128, 128] left mantissa matrix
        left_exp: [128, 4] left exponent matrix
        right_mant: [128, 128] right mantissa matrix
        right_exp: [128, 4] right exponent matrix
        B, C, V: Matrix dimension parameters
        exp_bias: Exponent bias (default: 15)

    Returns:
        np.array: FP16 results as uint16 array
    """
    print(f"\n   [FP-REF] Computing floating-point reference...")

    # Convert GFP to float
    def gfp_to_float(mant_matrix, exp_matrix):
        rows, cols = mant_matrix.shape
        float_matrix = np.zeros((rows, cols), dtype=np.float64)
        for r in range(rows):
            for c in range(cols):
                group_idx = c // 32
                exp_val = int(exp_matrix[r, group_idx])
                mant_val = int(mant_matrix[r, c])
                if exp_val == 0:
                    float_matrix[r, c] = 0.0
                else:
                    scale = 2.0 ** (exp_val - exp_bias)
                    float_matrix[r, c] = mant_val * scale
        return float_matrix

    left_float = gfp_to_float(left_mant, left_exp)
    right_float = gfp_to_float(right_mant, right_exp)

    # Extract submatrices
    left_sub = left_float[:B*V, :]  # (B*V) x 128
    right_sub = right_float[:C*V, :]  # (C*V) x 128

    # Perform float matmul with V-loop accumulation
    result = np.zeros((B, C), dtype=np.float64)
    for b in range(B):
        for c in range(C):
            for v in range(V):
                left_vec = left_sub[b*V + v, :]  # 128 elements
                right_vec = right_sub[c*V + v, :]  # 128 elements
                result[b, c] += np.dot(left_vec, right_vec)

    # Convert to FP16
    result_fp16 = result.astype(np.float16).flatten()
    results_fp = np.array([np.frombuffer(val.tobytes(), dtype=np.uint16)[0] for val in result_fp16], dtype=np.uint16)

    print(f"   [FP-REF] Generated {len(results_fp)} FP16 results ({B}x{C})")
    print(f"   [FP-REF] First 4 values: {' '.join(f'0x{v:04x}' for v in results_fp[:min(4, len(results_fp))])}")

    return results_fp


# =============================================================================
# MAIN
# =============================================================================

def main():
    script_dir = get_script_dir()

    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description='Generate HARDWARE-ACCURATE GFP GEMM golden reference',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This script generates golden references using the HARDWARE-ACCURATE algorithm
that matches the RTL implementation. It also computes EMULATOR-BASED and
FLOATING-POINT references for comparison.

Output files:
  golden_B{B}_C{C}_V{V}.hex     - HARDWARE-ACCURATE reference (use this!)
  golden_B{B}_C{C}_V{V}_emu_NEW.hex - Emulator-based (for comparison)
  out.hex                       - Same as hardware-accurate reference
        """
    )
    parser.add_argument('--B', type=int, default=128, help='Output rows (batch size)')
    parser.add_argument('--C', type=int, default=128, help='Output columns')
    parser.add_argument('--V', type=int, default=1, help='Inner dimension multiplier (V Native Vectors)')
    parser.add_argument('--left', type=str, default=None, help='Path to left matrix hex file')
    parser.add_argument('--right', type=str, default=None, help='Path to right matrix hex file')
    parser.add_argument('--output', type=str, default=None, help='Path to output golden hex file')
    args = parser.parse_args()

    B, C, V = args.B, args.C, args.V

    # Validate parameters
    if B * V > 128 or C * V > 128:
        print(f"ERROR: Invalid parameters! BxV={B*V} and CxV={C*V} must both be <= 128")
        sys.exit(1)

    # Set default file paths
    left_hex_path = args.left if args.left else os.path.join(script_dir, 'left.hex')
    right_hex_path = args.right if args.right else os.path.join(script_dir, 'right.hex')
    output_path = args.output if args.output else os.path.join(script_dir, f'golden_B{B}_C{C}_V{V}.hex')

    print("=" * 80)
    print("HARDWARE-ACCURATE GFP GEMM Reference Generation")
    print("=" * 80)
    print(f"\nConfiguration: B={B}, C={C}, V={V}")
    print(f"  Matrix A: {B} x {128*V} (uses {B*V} Native Vectors)")
    print(f"  Matrix B: {128*V} x {C} (uses {C*V} Native Vectors)")
    print(f"  Output:   {B} x {C} = {B*C} results")

    # Load matrices
    print("\n1. Loading matrices from hex files...")
    print(f"   Left matrix: {left_hex_path}")
    print(f"   Right matrix: {right_hex_path}")

    exp_left_raw, man_left_raw = load_hex_file(left_hex_path)
    left_exp_torch = decode_exponents(exp_left_raw)
    left_exp = left_exp_torch.numpy()
    left_mant = decode_mantissas(man_left_raw)

    exp_right_raw, man_right_raw = load_hex_file(right_hex_path)
    right_exp_torch = decode_exponents(exp_right_raw)
    right_exp = right_exp_torch.numpy()
    right_mant = decode_mantissas(man_right_raw)

    print(f"   Left matrix: {left_mant.shape}, exponents: {left_exp.shape}")
    print(f"   Right matrix: {right_mant.shape}, exponents: {right_exp.shape}")

    # Compute results using all three methods
    results_hardware = None
    results_emulator = None
    results_fp = None

    # 1. HARDWARE-ACCURATE (primary)
    print("\n2. Computing with HARDWARE-ACCURATE Algorithm (for golden generation)...")
    hw_compute = HardwareGFPCompute(exp_bits=5, exp_bias=15, group_size=32)
    results_hardware = hw_compute.compute_gemm_with_bcv(left_mant, left_exp, right_mant, right_exp, B, C, V)
    print(f"   [HARDWARE] Generated {len(results_hardware)} FP16 results ({B}x{C})")
    print(f"   [HARDWARE] First 4 values: {' '.join(f'0x{v:04x}' for v in results_hardware[:4])}")

    # 2. EMULATOR-BASED (for comparison)
    print("\n3. Computing with EMULATOR Algorithm (for comparison only)...")
    results_emulator = compute_emulator_golden(B, C, V, left_mant, left_exp, right_mant, right_exp)

    # 3. FLOATING-POINT (for comparison)
    print("\n4. Computing with FLOATING-POINT Reference (for comparison)...")
    results_fp = compute_fp_reference(left_mant, left_exp, right_mant, right_exp, B, C, V)

    # Compare all three methods
    print("\n" + "=" * 80)
    print("COMPARISON: Hardware vs Emulator vs Floating-Point")
    print("=" * 80)

    def compare_results(name1, results1, name2, results2):
        """Compare two result arrays and print metrics."""
        if results1 is None or results2 is None:
            print(f"   Cannot compare: {name1 if results1 is None else name2} not available")
            return

        # Convert to float
        float1 = np.array([np.frombuffer(struct.pack('<H', v), dtype=np.float16)[0] for v in results1], dtype=np.float32)
        float2 = np.array([np.frombuffer(struct.pack('<H', v), dtype=np.float16)[0] for v in results2], dtype=np.float32)

        # Compute metrics
        exact_matches = np.sum(results1 == results2)
        total = len(results1)
        match_rate = 100.0 * exact_matches / total

        abs_errors = np.abs(float1 - float2)
        rmse = np.sqrt(np.mean((float1 - float2)**2))
        max_error = np.max(abs_errors)
        mean_error = np.mean(abs_errors)

        print(f"\n{name1} vs {name2}:")
        print(f"  Exact FP16 matches: {exact_matches}/{total} ({match_rate:.1f}%)")
        print(f"  RMSE:               {rmse:.6e}")
        print(f"  Max absolute error: {max_error:.6e}")
        print(f"  Mean absolute error: {mean_error:.6e}")

    compare_results("HARDWARE", results_hardware, "EMULATOR", results_emulator)
    compare_results("HARDWARE", results_hardware, "FP-REF", results_fp)
    compare_results("EMULATOR", results_emulator, "FP-REF", results_fp)

    # Write output files
    print("\n" + "=" * 80)
    print("5. Writing output files...")

    # HARDWARE-ACCURATE golden (primary output)
    print(f"   Writing HARDWARE-ACCURATE golden to {output_path}...")
    with open(output_path, 'w') as f:
        for val in results_hardware:
            f.write(f"{val:04x}\n")
    print(f"   [OK] Wrote {len(results_hardware)} values")

    # Also write to out.hex for backward compatibility
    if args.output is None:
        out_path = os.path.join(script_dir, 'out.hex')
        print(f"   Writing to {out_path}...")
        with open(out_path, 'w') as f:
            for val in results_hardware:
                f.write(f"{val:04x}\n")
        print(f"   [OK] Wrote {len(results_hardware)} values")

    # EMULATOR golden (for comparison)
    if results_emulator is not None:
        emu_path = os.path.join(script_dir, f'golden_B{B}_C{C}_V{V}_emu.hex')
        print(f"   Writing EMULATOR reference to {emu_path}...")
        with open(emu_path, 'w') as f:
            for val in results_emulator:
                f.write(f"{val:04x}\n")
        print(f"   [OK] Wrote {len(results_emulator)} values")

    # Verification
    print(f"\n6. Verification (first 16 HARDWARE-ACCURATE results):")
    num_to_show = min(16, len(results_hardware))
    for i in range(num_to_show):
        row = i // C
        col = i % C
        fp16_bits = results_hardware[i]
        fp16_val = np.frombuffer(struct.pack('<H', fp16_bits), dtype=np.float16)[0]
        print(f"   [{i:2d}] output[{row},{col}] = 0x{fp16_bits:04x} ({fp16_val:8.4f})")

    print("\n" + "=" * 80)
    print("Golden reference generation complete!")
    print("\nFiles generated:")
    print(f"  {output_path} - HARDWARE-ACCURATE reference (USE THIS FOR RTL VERIFICATION)")
    if args.output is None:
        print(f"  out.hex - Same as hardware-accurate reference")
    if results_emulator is not None:
        print(f"  golden_B{B}_C{C}_V{V}_emu.hex - Emulator reference (for comparison)")
    print("=" * 80)


if __name__ == '__main__':
    main()
